name: drum_classifier
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - python=3.12.7
  - pandas
  - tensorflow
  - scipy
  - matplotlib
  - ipykernel
  - tqdm
  - numpy
  - seaborn
  - scikit-learn
  - jupyter
  - pip
  - pip:
    - crepe==0.0.16
    - tensorflow==2.18.0
    - keras==3.7.0
