---
title: "PCR-Project"
output: html_document
date: "2024-11-13"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(ISLR)
library(tidyverse) 
library(tidymodels)
library(knitr)
library(rpart.plot)
library(caret)
library(dplyr)
```

```{r}
drums <- read.csv("sample_features_balanced.csv") |>
  drop_na() |>
  mutate(label = as.factor(label)) 





```

```{r}
set.seed(445)

data_split <- initial_split(drums, 0.75, strata = label)
training_drums <- training(data_split)
testing_drums <- testing(data_split)

tree_spec <- decision_tree() |>
  set_engine('rpart') |>
  set_mode("classification")

tree_fit <- tree_spec |>
  fit(label ~. , data = training_drums)


predictions <- tree_fit |>
  predict(testing_drums) |>
  pull(.pred_class)

metrics <- metric_set(accuracy)

model_performance <- testing_drums %>%
 mutate(predictions = predictions) %>%
 metrics(truth = label, estimate = predictions)


model_performance$.estimate

confmatrix <- confusionMatrix(testing_drums$label,predictions)
confmatrix$table

tree_engine <- extract_fit_engine(tree_fit)
rpart.plot(tree_engine, roundint =  FALSE)

```












```{r}
tree_spec <- decision_tree(
  cost_complexity = tune()) |>
  set_engine('rpart') |>
  set_mode("classification")



# Define a grid for the cost_complexity parameter
tree_grid <- grid_regular(cost_complexity(range = c(0.001, 0.1)), levels = 1)



# Define a cross-validation strategy

folds <- vfold_cv(training_drums, v = 10)

# Perform cross-validation
tree_tune <- tune_grid(
  tree_spec,
  label ~ .,
  resamples = folds,
  grid = tree_grid,
  metrics = metric_set(accuracy)
)

# Collect the results
best_tree <- tree_tune |> select_best(metric = "accuracy" )

best_tree


# Print the best tree complexity parameter




```

```{r}
tree_spec <- decision_tree(cost_complexity = best_tree$cost_complexity) |>
  set_engine('rpart') |>
  set_mode("classification")

tree_fit <- tree_spec |>
  fit(label ~. , data = training_drums)

predictions <- tree_fit |>
  predict(testing_drums) |>
  pull(.pred_class)

predictions
```

```{r}
metrics <- metric_set(accuracy)

model_performance <- testing_drums %>%
 mutate(predictions = predictions) %>%
 metrics(truth = label, estimate = predictions)

model_performance$.estimate


confmatrix_optimal <- confusionMatrix(testing_drums$label,predictions)
confmatrix_optimal$table

tree_engine <- extract_fit_engine(tree_fit)
rpart.plot(tree_engine, roundint =  FALSE)


```


```












